export enum AuditAction {
  // Auth
  LOGIN = 'AUTH_LOGIN',
  LOGIN_FAILED = 'AUTH_LOGIN_FAILED',
  LOGOUT = 'AUTH_LOGOUT',
  TOKEN_REFRESHED = 'AUTH_TOKEN_REFRESHED',
  ACCOUNT_LOCKED = 'AUTH_ACCOUNT_LOCKED',

  // Users
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DELETED = 'USER_DELETED',
  USER_RESTORED = 'USER_RESTORED',
  PASSWORD_CHANGED = 'USER_PASSWORD_CHANGED',
  PASSWORD_RESET = 'USER_PASSWORD_RESET',

  // Roles
  ROLE_CREATED = 'ROLE_CREATED',
  ROLE_UPDATED = 'ROLE_UPDATED',
  ROLE_DELETED = 'ROLE_DELETED',
  ROLE_ASSIGNED = 'ROLE_ASSIGNED',

  // Permissions
  PERMISSION_CREATED = 'PERMISSION_CREATED',
  PERMISSION_UPDATED = 'PERMISSION_UPDATED',
  PERMISSION_DELETED = 'PERMISSION_DELETED',
  PERMISSION_ASSIGNED = 'PERMISSION_ASSIGNED',
  PERMISSION_REVOKED = 'PERMISSION_REVOKED',

  // Sports Resources
  SPORT_CREATED = 'SPORT_CREATED',
  SPORT_UPDATED = 'SPORT_UPDATED',
  SPORT_DELETED = 'SPORT_DELETED',
  ORGANIZATION_CREATED = 'ORGANIZATION_CREATED',
  ORGANIZATION_UPDATED = 'ORGANIZATION_UPDATED',
  ORGANIZATION_DELETED = 'ORGANIZATION_DELETED',
  TEAM_CREATED = 'TEAM_CREATED',
  TEAM_UPDATED = 'TEAM_UPDATED',
  TEAM_DELETED = 'TEAM_DELETED',
  PLAYER_CREATED = 'PLAYER_CREATED',
  PLAYER_UPDATED = 'PLAYER_UPDATED',
  PLAYER_DELETED = 'PLAYER_DELETED',
  MATCH_CREATED = 'MATCH_CREATED',
  MATCH_UPDATED = 'MATCH_UPDATED',
  MATCH_DELETED = 'MATCH_DELETED',
  TOURNAMENT_CREATED = 'TOURNAMENT_CREATED',
  TOURNAMENT_UPDATED = 'TOURNAMENT_UPDATED',
  TOURNAMENT_DELETED = 'TOURNAMENT_DELETED',

  // Settings
  SETTINGS_UPDATED = 'SETTINGS_UPDATED',

  // Data
  DATA_EXPORTED = 'DATA_EXPORTED',
  REPORT_GENERATED = 'REPORT_GENERATED',
}

export enum AuditStatus {
  SUCCESS = 'success',
  FAILURE = 'failure',
}

export enum AuditSeverity {
  LOW = 'low',
  MEDIUM = 'medium',
  HIGH = 'high',
  CRITICAL = 'critical',
}
